server:
  port: 8080

spring:
  application:
    name: hotel-backend
  config:
    import: optional:nacos:application.yml

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@hotel-oracle:1521/FREEPDB1
    username: hotel_user
    password: 123456

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  Jackson:
    serialization:
      write-dates-as-timestamps: false

minio:
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: xxxxxx
    access-key-secret: xxxxxx
    bucket-name: hotelhotel

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

jwt:
  secret: "change-this-secret-to-a-very-long-random-string"
  expires-hours: 12

deepseek:
  api:
    url: https://api.deepseek.com/v1/chat/completions
    key: sk-xxxxxx
  model: deepseek-chat
