-- 切换到 PDB ORCLPDB
ALTER PLUGGABLE DATABASE ORCLPDB OPEN;
ALTER SESSION SET CONTAINER = ORCLPDB;

-- 创建表空间
CREATE TABLESPACE hotel_ts
DATAFILE 'D:/tablespace/hotel_ts01.dbf' SIZE 500M
AUTOEXTEND ON NEXT 100M MAXSIZE 2G
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;

-- 创建普通用户 hotel_user，指定默认表空间和临时表空间
CREATE USER hotel_user
IDENTIFIED BY 123456
DEFAULT TABLESPACE hotel_ts
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON hotel_ts;

-- 授予基本权限
GRANT CREATE SESSION TO hotel_user;
GRANT CREATE TABLE TO hotel_user;
GRANT CREATE VIEW TO hotel_user;
GRANT CREATE SEQUENCE TO hotel_user;
GRANT CREATE TRIGGER TO hotel_user;
GRANT CREATE PROCEDURE TO hotel_user;
GRANT CREATE TYPE TO hotel_user;        
GRANT UNLIMITED TABLESPACE TO hotel_user; 

CONNECT hotel_user/123456@ORCLPDB;