-- 清理已存在的表（Oracle 不支持 IF EXISTS，若表不存在会报错，请根据环境处理）
DROP TABLE vacancy_statistics CASCADE CONSTRAINTS PURGE;
DROP TABLE vip_level_policy CASCADE CONSTRAINTS PURGE;
DROP TABLE wallet_transaction CASCADE CONSTRAINTS PURGE;
DROP TABLE payment_record CASCADE CONSTRAINTS PURGE;
DROP TABLE wallet_account CASCADE CONSTRAINTS PURGE;
DROP TABLE bookings CASCADE CONSTRAINTS PURGE;
DROP TABLE room_maintenance CASCADE CONSTRAINTS PURGE;
DROP TABLE room_price_strategy CASCADE CONSTRAINTS PURGE;
DROP TABLE room_images CASCADE CONSTRAINTS PURGE;
DROP TABLE room CASCADE CONSTRAINTS PURGE;
DROP TABLE room_type CASCADE CONSTRAINTS PURGE;
DROP TABLE users CASCADE CONSTRAINTS PURGE;
DROP TABLE hotel CASCADE CONSTRAINTS PURGE;

DROP SEQUENCE seq_hotel;
DROP SEQUENCE seq_users;
DROP SEQUENCE seq_room_type;
DROP SEQUENCE seq_room_price_strategy;
DROP SEQUENCE seq_room_images;
DROP SEQUENCE seq_room;
DROP SEQUENCE seq_room_maintenance;
DROP SEQUENCE seq_bookings;
DROP SEQUENCE seq_wallet_account;
DROP SEQUENCE seq_wallet_transaction;
DROP SEQUENCE seq_payment_record;

-- 创建表 hotel
CREATE TABLE hotel (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR2(100) NOT NULL,
    address          VARCHAR2(255) NOT NULL,
    city             VARCHAR2(50) NOT NULL,
    phone            VARCHAR2(20) NOT NULL,
    star_level       NUMBER(3) DEFAULT 0 NOT NULL,
    status           NUMBER(3) DEFAULT 1 NOT NULL,
    introduction     CLOB NOT NULL,
    hero_image_url   VARCHAR2(500) NOT NULL,
    gallery_images   CLOB,
    created_time     DATE DEFAULT SYSDATE NOT NULL,
    updated_time     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_hotel_name UNIQUE (name)
);

COMMENT ON TABLE hotel IS 'Hotel Information Table';
COMMENT ON COLUMN hotel.id IS 'Hotel ID';
COMMENT ON COLUMN hotel.name IS 'Hotel name';
COMMENT ON COLUMN hotel.address IS 'Hotel address';
COMMENT ON COLUMN hotel.city IS 'City';
COMMENT ON COLUMN hotel.phone IS 'Contact phone (supports domestic and international numbers)';
COMMENT ON COLUMN hotel.star_level IS 'Star rating (0 = unrated)';
COMMENT ON COLUMN hotel.status IS 'Status (1 = open, 0 = closed)';
COMMENT ON COLUMN hotel.introduction IS 'Hotel introduction';
COMMENT ON COLUMN hotel.hero_image_url IS 'Hero image URL';
COMMENT ON COLUMN hotel.gallery_images IS 'Gallery images (comma-separated URLs)';
COMMENT ON COLUMN hotel.created_time IS 'Creation time';
COMMENT ON COLUMN hotel.updated_time IS 'Update time';

CREATE INDEX idx_city ON hotel(city);

-- 创建表 users
CREATE TABLE users (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username           VARCHAR2(20) NOT NULL,
    password           VARCHAR2(255) NOT NULL,
    role               VARCHAR2(10) DEFAULT 'USER' NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    vip_level          NUMBER(3) DEFAULT 0 NOT NULL,
    total_consumption  NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    phone              VARCHAR2(20) NOT NULL,
    email              VARCHAR2(255),
    status             VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'DISABLED')),
    created_at         DATE DEFAULT SYSDATE NOT NULL,
    updated_at         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT uq_users_phone UNIQUE (phone),
    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_username_length CHECK (LENGTH(username) BETWEEN 3 AND 20),
    CONSTRAINT chk_password_length CHECK (LENGTH(password) BETWEEN 6 AND 50),
    CONSTRAINT chk_phone_format CHECK (REGEXP_LIKE(phone, '^(1[3-9][0-9]{9}|\+?[1-9][0-9]{1,14})$')),
    CONSTRAINT chk_email_format CHECK (email IS NULL OR REGEXP_LIKE(email, '^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'))
);

COMMENT ON TABLE users IS 'User Table';
COMMENT ON COLUMN users.id IS 'User ID';
COMMENT ON COLUMN users.username IS 'Username, 3-20 characters, supports letters, numbers, underscore, Chinese';
COMMENT ON COLUMN users.password IS 'Password, 6-50 characters';
COMMENT ON COLUMN users.role IS 'User role';
COMMENT ON COLUMN users.vip_level IS 'VIP level, 0-4';
COMMENT ON COLUMN users.total_consumption IS 'Annual total consumption (used for VIP upgrade calculation)';
COMMENT ON COLUMN users.phone IS 'Contact phone (supports domestic 11-digit and international numbers, including + and -)';
COMMENT ON COLUMN users.email IS 'Email, optional';
COMMENT ON COLUMN users.status IS 'Account status';
COMMENT ON COLUMN users.created_at IS 'Creation time';
COMMENT ON COLUMN users.updated_at IS 'Update time';

-- 创建表 vip_level_policy
CREATE TABLE vip_level_policy (
    vip_level          NUMBER(3) PRIMARY KEY,
    name           VARCHAR2(50) NOT NULL,
    discount_rate  NUMBER(4,3) DEFAULT 1.000 NOT NULL,
    checkout_hour  NUMBER(3) DEFAULT 12 NOT NULL,
    description    VARCHAR2(255),
    created_at     DATE DEFAULT SYSDATE NOT NULL,
    updated_at     DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON TABLE vip_level_policy IS 'VIP Level Benefits Policy';
COMMENT ON COLUMN vip_level_policy.vip_level IS 'VIP level';
COMMENT ON COLUMN vip_level_policy.name IS 'Level name';
COMMENT ON COLUMN vip_level_policy.discount_rate IS 'Base discount rate';
COMMENT ON COLUMN vip_level_policy.checkout_hour IS 'Checkout hour (0-23)';
COMMENT ON COLUMN vip_level_policy.description IS 'Benefits description';
COMMENT ON COLUMN vip_level_policy.created_at IS 'Creation time';
COMMENT ON COLUMN vip_level_policy.updated_at IS 'Update time';

-- 创建表 room_type
CREATE TABLE room_type (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id         NUMBER(19) NOT NULL,
    name             VARCHAR2(80) NOT NULL,
    type             VARCHAR2(60) NOT NULL,
    theme_color      CHAR(7) DEFAULT '#2F54EB' NOT NULL,
    description      CLOB,
    price_per_night  NUMBER(10,2) NOT NULL,
    total_count      NUMBER(10) DEFAULT 0 NOT NULL,
    available_count  NUMBER(10) DEFAULT 0 NOT NULL,
    images           CLOB,
    amenities        CLOB,
    area_sqm         NUMBER(6,2),
    bed_type         VARCHAR2(30),
    max_guests       NUMBER(10) DEFAULT 2 NOT NULL,
    is_active        NUMBER(3) DEFAULT 1 NOT NULL,
    created_time     DATE DEFAULT SYSDATE NOT NULL,
    updated_time     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_room_type_hotel FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE
);

COMMENT ON TABLE room_type IS 'Room Type Table';
COMMENT ON COLUMN room_type.id IS 'Room Type ID';
COMMENT ON COLUMN room_type.hotel_id IS 'Hotel ID';
COMMENT ON COLUMN room_type.name IS 'Room type name (frontend display name)';
COMMENT ON COLUMN room_type.type IS 'Room type classification (e.g., Deluxe / Standard)';
COMMENT ON COLUMN room_type.theme_color IS 'Frontend theme color (#RRGGBB)';
COMMENT ON COLUMN room_type.description IS 'Room type description';
COMMENT ON COLUMN room_type.price_per_night IS 'Base price (CNY/night)';
COMMENT ON COLUMN room_type.total_count IS 'Total number of rooms in this type';
COMMENT ON COLUMN room_type.available_count IS 'Current available count';
COMMENT ON COLUMN room_type.images IS 'Room type images (comma-separated URLs)';
COMMENT ON COLUMN room_type.amenities IS 'Amenities list in JSON';
COMMENT ON COLUMN room_type.area_sqm IS 'Area (square meters)';
COMMENT ON COLUMN room_type.bed_type IS 'Bed type';
COMMENT ON COLUMN room_type.max_guests IS 'Maximum guests';
COMMENT ON COLUMN room_type.is_active IS 'Status (1 = active, 0 = inactive)';
COMMENT ON COLUMN room_type.created_time IS 'Creation time';
COMMENT ON COLUMN room_type.updated_time IS 'Update time';

CREATE INDEX idx_room_type_hotel ON room_type(hotel_id);
CREATE INDEX idx_room_type_active ON room_type(hotel_id, is_active);

-- 创建表 room
CREATE TABLE room (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id           NUMBER(19) NOT NULL,
    room_type_id       NUMBER(19) NOT NULL,
    room_number        VARCHAR2(20) NOT NULL,
    floor              NUMBER(5),
    status             NUMBER(3) DEFAULT 1 NOT NULL,
    last_checkout_time DATE,
    created_time       DATE DEFAULT SYSDATE NOT NULL,
    updated_time       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_room_hotel FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE,
    CONSTRAINT fk_room_room_type FOREIGN KEY (room_type_id) REFERENCES room_type(id) ON DELETE CASCADE,
    CONSTRAINT uk_room_hotel_no UNIQUE (hotel_id, room_number)
);

COMMENT ON TABLE room IS 'Room Table';
COMMENT ON COLUMN room.id IS 'Room ID';
COMMENT ON COLUMN room.hotel_id IS 'Hotel ID';
COMMENT ON COLUMN room.room_type_id IS 'Room Type ID';
COMMENT ON COLUMN room.room_number IS 'Room number';
COMMENT ON COLUMN room.floor IS 'Floor';
COMMENT ON COLUMN room.status IS 'Room status (1 vacant, 2 booked, 3 occupied, 4 to be cleaned, 5 under maintenance)';
COMMENT ON COLUMN room.last_checkout_time IS 'Last checkout time';
COMMENT ON COLUMN room.created_time IS 'Creation time';
COMMENT ON COLUMN room.updated_time IS 'Update time';

CREATE INDEX idx_room_type ON room(room_type_id);
CREATE INDEX idx_room_status ON room(hotel_id, status);
CREATE INDEX idx_room_type_status ON room(room_type_id, status);

-- 创建表 room_images
CREATE TABLE room_images (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_type_id NUMBER(19) NOT NULL,
    url          VARCHAR2(1000) NOT NULL,
    is_primary   NUMBER(1) DEFAULT 0 NOT NULL,
    sort_order   NUMBER(10) DEFAULT 0 NOT NULL,
    created_at   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_room_images_type FOREIGN KEY (room_type_id) REFERENCES room_type(id) ON DELETE CASCADE
);

COMMENT ON TABLE room_images IS 'Room Type Images';

CREATE INDEX idx_room_images_type ON room_images(room_type_id);

-- 创建表 room_price_strategy
CREATE TABLE room_price_strategy (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id      NUMBER(19) NOT NULL,
    room_type_id  NUMBER(19) NOT NULL,
    strategy_type NUMBER(3) NOT NULL,
    start_date    DATE NOT NULL,
    end_date      DATE NOT NULL,
    price_adjust  NUMBER(10,2) DEFAULT 0.00,
    discount_rate NUMBER(3,2),
    vip_level     NUMBER(3),
    min_stay_days NUMBER(3) DEFAULT 1,
    status        NUMBER(3) DEFAULT 1 NOT NULL,
    created_time  DATE DEFAULT SYSDATE NOT NULL,
    updated_time  DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_price_strategy_hotel FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE,
    CONSTRAINT fk_price_strategy_type FOREIGN KEY (room_type_id) REFERENCES room_type(id) ON DELETE CASCADE
);

COMMENT ON TABLE room_price_strategy IS 'Room Price Strategy';

CREATE INDEX idx_price_strategy_rt ON room_price_strategy(room_type_id, start_date, end_date);

-- 创建表 room_maintenance
CREATE TABLE room_maintenance (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id          NUMBER(19) NOT NULL,
    maintenance_type VARCHAR2(50) NOT NULL,
    description      CLOB,
    start_time       DATE NOT NULL,
    end_time         DATE,
    operator         VARCHAR2(50) NOT NULL,
    status           NUMBER(3) DEFAULT 1 NOT NULL,
    created_time     DATE DEFAULT SYSDATE NOT NULL,
    updated_time     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_room_maintenance_room FOREIGN KEY (room_id) REFERENCES room(id) ON DELETE CASCADE
);

COMMENT ON TABLE room_maintenance IS 'Room Maintenance Records';

CREATE INDEX idx_room_maintenance_room ON room_maintenance(room_id);
CREATE INDEX idx_room_maintenance_status ON room_maintenance(status, start_time);

-- 创建表 bookings
CREATE TABLE bookings (
    id                   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id             NUMBER(19) NOT NULL,
    room_type_id         NUMBER(19) NOT NULL,
    room_id              NUMBER(19) NOT NULL,
    user_id              NUMBER(19) NOT NULL,
    start_time           DATE NOT NULL,
    end_time             DATE NOT NULL,
    status               VARCHAR2(30) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING','PENDING_CONFIRMATION','PENDING_PAYMENT','CONFIRMED','CHECKED_IN','CHECKED_OUT','CANCELLED','REFUND_REQUESTED','REFUNDED')),
    guests               NUMBER(10) DEFAULT 1 NOT NULL,
    amount               NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    original_amount      NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    discount_amount      NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    payable_amount       NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    paid_amount          NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    discount_rate        NUMBER(4,3) DEFAULT 1.000 NOT NULL,
    payment_status       VARCHAR2(20) DEFAULT 'UNPAID' NOT NULL CHECK (payment_status IN ('UNPAID','PAID','PARTIAL_REFUND','REFUNDED','WAIVED')),
    payment_method       VARCHAR2(40),
    payment_channel      VARCHAR2(40),
    wallet_transaction_id NUMBER(19),
    payment_record_id    NUMBER(19),
    currency             CHAR(3) DEFAULT 'CNY' NOT NULL,
    contact_name         VARCHAR2(100),
    contact_phone        VARCHAR2(30),
    remark               VARCHAR2(500),
    refund_reason        VARCHAR2(500),
    refund_requested_at  DATE,
    refund_approved_at   DATE,
    refund_rejected_at   DATE,
    refund_approved_by   NUMBER(19),
    created_at           DATE DEFAULT SYSDATE NOT NULL,
    updated_at           DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_bookings_hotel FOREIGN KEY (hotel_id) REFERENCES hotel(id),
    CONSTRAINT fk_bookings_room_type FOREIGN KEY (room_type_id) REFERENCES room_type(id),
    CONSTRAINT fk_bookings_room FOREIGN KEY (room_id) REFERENCES room(id),
    CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMENT ON TABLE bookings IS 'Booking Table';

CREATE INDEX idx_bookings_user ON bookings(user_id);
CREATE INDEX idx_bookings_status ON bookings(status);
CREATE INDEX idx_bookings_room ON bookings(room_id);
CREATE INDEX idx_bookings_room_period_full ON bookings(room_id, start_time, end_time);
CREATE INDEX idx_bookings_period ON bookings(start_time, end_time);
CREATE INDEX idx_bookings_room_type_period ON bookings(room_type_id, start_time);
CREATE INDEX idx_bookings_room_type_room ON bookings(room_type_id, room_id, start_time);

-- 创建表 vacancy_statistics
CREATE TABLE vacancy_statistics (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hotel_id         NUMBER(19) NOT NULL,
    room_type_id     NUMBER(19) NOT NULL,
    stat_date        DATE NOT NULL,
    stat_hour        NUMBER(3),
    total_rooms      NUMBER(10) DEFAULT 0 NOT NULL,
    available_rooms  NUMBER(10) DEFAULT 0 NOT NULL,
    occupied_rooms   NUMBER(10) DEFAULT 0 NOT NULL,
    reserved_rooms   NUMBER(10) DEFAULT 0 NOT NULL,
    maintenance_rooms NUMBER(10) DEFAULT 0 NOT NULL,
    locked_rooms     NUMBER(10) DEFAULT 0 NOT NULL,
    vacancy_count    NUMBER(10,2) DEFAULT 0.00 NOT NULL,
    vacancy_rate     NUMBER(5,4) DEFAULT 0.0000 NOT NULL,
    occupancy_rate   NUMBER(5,4) DEFAULT 0.0000 NOT NULL,
    booking_rate     NUMBER(5,4) DEFAULT 0.0000 NOT NULL,
    average_price    NUMBER(10,2),
    created_at       DATE DEFAULT SYSDATE NOT NULL,
    updated_at       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_vacancy_stats_hotel FOREIGN KEY (hotel_id) REFERENCES hotel(id) ON DELETE CASCADE,
    CONSTRAINT fk_vacancy_stats_room_type FOREIGN KEY (room_type_id) REFERENCES room_type(id) ON DELETE CASCADE,
    CONSTRAINT uq_vacancy_stats UNIQUE (hotel_id, room_type_id, stat_date, stat_hour)
);

COMMENT ON TABLE vacancy_statistics IS 'Vacancy Statistics Table';
COMMENT ON COLUMN vacancy_statistics.id IS 'Statistics ID';
COMMENT ON COLUMN vacancy_statistics.hotel_id IS 'Hotel ID';
COMMENT ON COLUMN vacancy_statistics.room_type_id IS 'Room Type ID';
COMMENT ON COLUMN vacancy_statistics.stat_date IS 'Statistics date';
COMMENT ON COLUMN vacancy_statistics.stat_hour IS 'Statistics hour (0-23), NULL for daily total';
COMMENT ON COLUMN vacancy_statistics.total_rooms IS 'Total rooms';
COMMENT ON COLUMN vacancy_statistics.available_rooms IS 'Available rooms';
COMMENT ON COLUMN vacancy_statistics.occupied_rooms IS 'Occupied rooms';
COMMENT ON COLUMN vacancy_statistics.reserved_rooms IS 'Booked rooms';
COMMENT ON COLUMN vacancy_statistics.maintenance_rooms IS 'Maintenance rooms';
COMMENT ON COLUMN vacancy_statistics.locked_rooms IS 'Locked rooms';
COMMENT ON COLUMN vacancy_statistics.vacancy_count IS 'Vacant count';
COMMENT ON COLUMN vacancy_statistics.vacancy_rate IS 'Vacancy rate (0-1)';
COMMENT ON COLUMN vacancy_statistics.occupancy_rate IS 'Occupancy rate (0-1)';
COMMENT ON COLUMN vacancy_statistics.booking_rate IS 'Booking rate (0-1)';
COMMENT ON COLUMN vacancy_statistics.average_price IS 'Average price';
COMMENT ON COLUMN vacancy_statistics.created_at IS 'Creation time';
COMMENT ON COLUMN vacancy_statistics.updated_at IS 'Update time';

CREATE INDEX idx_vacancy_stats_date ON vacancy_statistics(stat_date);
CREATE INDEX idx_vacancy_stats_room_type_date ON vacancy_statistics(room_type_id, stat_date);
CREATE INDEX idx_vacancy_stats_hotel_date ON vacancy_statistics(hotel_id, stat_date);

-- 创建表 wallet_account
CREATE TABLE wallet_account (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER(19) NOT NULL,
    balance        NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    frozen_balance NUMBER(12,2) DEFAULT 0.00 NOT NULL,
    status         VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE', 'FROZEN')),
    created_at     DATE DEFAULT SYSDATE NOT NULL,
    updated_at     DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_wallet_account_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uq_wallet_account_user UNIQUE (user_id)
);

COMMENT ON TABLE wallet_account IS 'User Wallet Account';

-- 创建表 wallet_transaction
CREATE TABLE wallet_transaction (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id       NUMBER(19) NOT NULL,
    user_id         NUMBER(19) NOT NULL,
    booking_id      NUMBER(19),
    type            VARCHAR2(20) NOT NULL CHECK (type IN ('RECHARGE', 'PAYMENT', 'REFUND', 'ADJUST')),
    direction       VARCHAR2(3) NOT NULL CHECK (direction IN ('IN', 'OUT')),
    amount          NUMBER(12,2) NOT NULL,
    balance_after   NUMBER(12,2) NOT NULL,
    payment_channel VARCHAR2(40),
    reference_no    VARCHAR2(100),
    remark          VARCHAR2(255),
    created_at      DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_wallet_tx_wallet FOREIGN KEY (wallet_id) REFERENCES wallet_account(id) ON DELETE CASCADE,
    CONSTRAINT fk_wallet_tx_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wallet_tx_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE SET NULL
);

COMMENT ON TABLE wallet_transaction IS 'Wallet Transaction Ledger';

CREATE INDEX idx_wallet_tx_user ON wallet_transaction(user_id, id);
CREATE INDEX idx_wallet_tx_booking ON wallet_transaction(booking_id);

-- 创建表 payment_record
CREATE TABLE payment_record (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id   NUMBER(19) NOT NULL,
    user_id      NUMBER(19) NOT NULL,
    amount       NUMBER(12,2) NOT NULL,
    method       VARCHAR2(40) NOT NULL,
    channel      VARCHAR2(40),
    status       VARCHAR2(20) DEFAULT 'PAID' NOT NULL CHECK (status IN ('PENDING', 'PAID', 'REFUNDED', 'PARTIAL_REFUND')),
    paid_at      DATE,
    refunded_at  DATE,
    reference_no VARCHAR2(100),
    created_at   DATE DEFAULT SYSDATE NOT NULL,
    updated_at   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_payment_record_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
    CONSTRAINT fk_payment_record_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

COMMENT ON TABLE payment_record IS 'Direct Payment Record';

CREATE INDEX idx_payment_record_user ON payment_record(user_id, id);
